// Copyright 2026 HPActor Contributors
// (Apache 2.0 license header)
#pragma once

#include <hpactor/adt/id.hpp>
#include <hpactor/adt/tags.hpp>

#include <atomic>

namespace hpactor {

/// \brief Globally unique per-message identifier.
///
/// Used for deduplication, delivery tracking, ask correlation, and tracing.
/// Generated by \c generate_message_id() with a monotonic sequence per
/// process — no coordination across nodes. Combine with a \c NodeIdentity
/// for cluster-wide uniqueness.
///
/// \note Thread safety: \c generate_message_id() is lock-free (atomic
///       fetch_add). \c MessageId values are trivially copyable and safe to
///       share across threads.
using MessageId = Id<MessageTag>;

/// \brief Generate a monotonic, globally unique \c MessageId.
///
/// Produces IDs from a process-local atomic counter starting at 1.
/// IDs are unique within the process lifetime; wrap is practically
/// impossible (64-bit counter).
///
/// \return A new \c MessageId with a monotonically increasing value.
/// \note Thread safety: Lock-free, safe to call from any thread.
inline MessageId generate_message_id() {
    static std::atomic<uint64_t> next_id_{1};
    return MessageId(next_id_.fetch_add(1));
}

} // namespace hpactor
