if(EXISTS "/Users/skg7on/Workspace/Projects/HPActor/.claude/worktrees/refactor-actor-system-v2/build-asan/tests/unit/ref/test_unit_ref[1]_tests.cmake")
  include("/Users/skg7on/Workspace/Projects/HPActor/.claude/worktrees/refactor-actor-system-v2/build-asan/tests/unit/ref/test_unit_ref[1]_tests.cmake")
else()
  add_test(test_unit_ref_NOT_BUILT test_unit_ref_NOT_BUILT)
endif()
