if(EXISTS "/Users/skg7on/Workspace/Projects/HPActor/.claude/worktrees/refactor-actor-system-v2/build-main/tests/unit/adt/test_unit_adt[1]_tests.cmake")
  include("/Users/skg7on/Workspace/Projects/HPActor/.claude/worktrees/refactor-actor-system-v2/build-main/tests/unit/adt/test_unit_adt[1]_tests.cmake")
else()
  add_test(test_unit_adt_NOT_BUILT test_unit_adt_NOT_BUILT)
endif()
