if(EXISTS "/Users/skg7on/Workspace/Projects/HPActor/.claude/worktrees/refactor-actor-system-v2/build-asan/tests/system/test_system[1]_tests.cmake")
  include("/Users/skg7on/Workspace/Projects/HPActor/.claude/worktrees/refactor-actor-system-v2/build-asan/tests/system/test_system[1]_tests.cmake")
else()
  add_test(test_system_NOT_BUILT test_system_NOT_BUILT)
endif()
