if(EXISTS "/Users/skg7on/Workspace/Projects/HPActor/.claude/worktrees/refactor-actor-system-v2/build-asan/tests/unit/net/test_unit_net[1]_tests.cmake")
  include("/Users/skg7on/Workspace/Projects/HPActor/.claude/worktrees/refactor-actor-system-v2/build-asan/tests/unit/net/test_unit_net[1]_tests.cmake")
else()
  add_test(test_unit_net_NOT_BUILT test_unit_net_NOT_BUILT)
endif()
