add_subdirectory(actor)
add_subdirectory(sched)
add_subdirectory(mailbox)
add_subdirectory(supervision)
add_subdirectory(metrics)
if(ENABLE_CLI)
    add_subdirectory(cli)
endif()
add_subdirectory(config)
add_subdirectory(log)
if(ENABLE_ACTOR_TRACING)
    add_subdirectory(tracing)
endif()
add_subdirectory(spawn)
add_subdirectory(rpc)
add_subdirectory(ref)
