// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hpactor/frame.proto
// Protobuf C++ Version: 7.34.1

#include "hpactor/frame.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace hpactor {
namespace net {

inline constexpr PbTraceContext::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        trace_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        span_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        tracestate_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        flags_{0u} {}

template <typename>
constexpr PbTraceContext::PbTraceContext(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PbTraceContext_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct PbTraceContextDefaultTypeInternal {
  constexpr PbTraceContextDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PbTraceContextDefaultTypeInternal() {}
  union {
    PbTraceContext _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PbTraceContextDefaultTypeInternal _PbTraceContext_default_instance_;

inline constexpr ActorMsgFrame::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        payload_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        sender_{nullptr},
        receiver_{nullptr},
        trace_context_{nullptr},
        message_id_{::uint64_t{0u}},
        type_tag_{0u},
        flags_{0u} {}

template <typename>
constexpr ActorMsgFrame::ActorMsgFrame(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ActorMsgFrame_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct ActorMsgFrameDefaultTypeInternal {
  constexpr ActorMsgFrameDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ActorMsgFrameDefaultTypeInternal() {}
  union {
    ActorMsgFrame _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ActorMsgFrameDefaultTypeInternal _ActorMsgFrame_default_instance_;
}  // namespace net
}  // namespace hpactor
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_hpactor_2fframe_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_hpactor_2fframe_2eproto = nullptr;
const ::uint32_t
    TableStruct_hpactor_2fframe_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::hpactor::net::PbTraceContext, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::hpactor::net::PbTraceContext, _impl_.trace_id_),
        PROTOBUF_FIELD_OFFSET(::hpactor::net::PbTraceContext, _impl_.span_id_),
        PROTOBUF_FIELD_OFFSET(::hpactor::net::PbTraceContext, _impl_.flags_),
        PROTOBUF_FIELD_OFFSET(::hpactor::net::PbTraceContext, _impl_.tracestate_),
        0,
        1,
        3,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::hpactor::net::ActorMsgFrame, _impl_._has_bits_),
        10, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::hpactor::net::ActorMsgFrame, _impl_.sender_),
        PROTOBUF_FIELD_OFFSET(::hpactor::net::ActorMsgFrame, _impl_.receiver_),
        PROTOBUF_FIELD_OFFSET(::hpactor::net::ActorMsgFrame, _impl_.type_tag_),
        PROTOBUF_FIELD_OFFSET(::hpactor::net::ActorMsgFrame, _impl_.message_id_),
        PROTOBUF_FIELD_OFFSET(::hpactor::net::ActorMsgFrame, _impl_.flags_),
        PROTOBUF_FIELD_OFFSET(::hpactor::net::ActorMsgFrame, _impl_.payload_),
        PROTOBUF_FIELD_OFFSET(::hpactor::net::ActorMsgFrame, _impl_.trace_context_),
        1,
        2,
        5,
        4,
        6,
        0,
        3,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::hpactor::net::PbTraceContext)},
        {11, sizeof(::hpactor::net::ActorMsgFrame)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::hpactor::net::_PbTraceContext_default_instance_._instance,
    &::hpactor::net::_ActorMsgFrame_default_instance_._instance,
};
const char descriptor_table_protodef_hpactor_2fframe_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023hpactor/frame.proto\022\013hpactor.net\032\024hpac"
    "tor/common.proto\"V\n\016PbTraceContext\022\020\n\010tr"
    "ace_id\030\001 \001(\014\022\017\n\007span_id\030\002 \001(\014\022\r\n\005flags\030\003"
    " \001(\r\022\022\n\ntracestate\030\004 \001(\t\"\335\001\n\rActorMsgFra"
    "me\022\'\n\006sender\030\001 \001(\0132\027.hpactor.PbActorAddr"
    "ess\022)\n\010receiver\030\002 \001(\0132\027.hpactor.PbActorA"
    "ddress\022\020\n\010type_tag\030\003 \001(\r\022\022\n\nmessage_id\030\004"
    " \001(\004\022\r\n\005flags\030\005 \001(\r\022\017\n\007payload\030\006 \001(\014\0222\n\r"
    "trace_context\030\007 \001(\0132\033.hpactor.net.PbTrac"
    "eContextb\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_hpactor_2fframe_2eproto_deps[1] = {
        &::descriptor_table_hpactor_2fcommon_2eproto,
};
static ::absl::once_flag descriptor_table_hpactor_2fframe_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_hpactor_2fframe_2eproto = {
    false,
    false,
    376,
    descriptor_table_protodef_hpactor_2fframe_2eproto,
    "hpactor/frame.proto",
    &descriptor_table_hpactor_2fframe_2eproto_once,
    descriptor_table_hpactor_2fframe_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_hpactor_2fframe_2eproto::offsets,
    file_level_enum_descriptors_hpactor_2fframe_2eproto,
    file_level_service_descriptors_hpactor_2fframe_2eproto,
};
namespace hpactor {
namespace net {
// ===================================================================

class PbTraceContext::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PbTraceContext>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PbTraceContext, _impl_._has_bits_);
};

PbTraceContext::PbTraceContext(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PbTraceContext_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:hpactor.net.PbTraceContext)
}
PROTOBUF_NDEBUG_INLINE PbTraceContext::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::hpactor::net::PbTraceContext& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        trace_id_(arena, from.trace_id_),
        span_id_(arena, from.span_id_),
        tracestate_(arena, from.tracestate_) {}

PbTraceContext::PbTraceContext(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PbTraceContext& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PbTraceContext_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PbTraceContext* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.flags_ = from._impl_.flags_;

  // @@protoc_insertion_point(copy_constructor:hpactor.net.PbTraceContext)
}
PROTOBUF_NDEBUG_INLINE PbTraceContext::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        trace_id_(arena),
        span_id_(arena),
        tracestate_(arena) {}

inline void PbTraceContext::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.flags_ = {};
}
PbTraceContext::~PbTraceContext() {
  // @@protoc_insertion_point(destructor:hpactor.net.PbTraceContext)
  SharedDtor(*this);
}
inline void PbTraceContext::SharedDtor(MessageLite& self) {
  PbTraceContext& this_ = static_cast<PbTraceContext&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.trace_id_.Destroy();
  this_._impl_.span_id_.Destroy();
  this_._impl_.tracestate_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PbTraceContext::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PbTraceContext(arena);
}
constexpr auto PbTraceContext::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PbTraceContext),
                                            alignof(PbTraceContext));
}
constexpr auto PbTraceContext::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PbTraceContext_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &PbTraceContext::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PbTraceContext>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PbTraceContext::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PbTraceContext>(), &PbTraceContext::ByteSizeLong,
              &PbTraceContext::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PbTraceContext, _impl_._cached_size_),
          false,
      },
      &PbTraceContext::kDescriptorMethods,
      &descriptor_table_hpactor_2fframe_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PbTraceContext_class_data_ =
        PbTraceContext::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PbTraceContext::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PbTraceContext_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PbTraceContext_class_data_.tc_table);
  return PbTraceContext_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 45, 2>
PbTraceContext::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PbTraceContext, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PbTraceContext_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::hpactor::net::PbTraceContext>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string tracestate = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 2, 0,
      PROTOBUF_FIELD_OFFSET(PbTraceContext, _impl_.tracestate_)}},
    // bytes trace_id = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(PbTraceContext, _impl_.trace_id_)}},
    // bytes span_id = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(PbTraceContext, _impl_.span_id_)}},
    // uint32 flags = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PbTraceContext, _impl_.flags_), 3>(),
     {24, 3, 0,
      PROTOBUF_FIELD_OFFSET(PbTraceContext, _impl_.flags_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes trace_id = 1;
    {PROTOBUF_FIELD_OFFSET(PbTraceContext, _impl_.trace_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes span_id = 2;
    {PROTOBUF_FIELD_OFFSET(PbTraceContext, _impl_.span_id_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // uint32 flags = 3;
    {PROTOBUF_FIELD_OFFSET(PbTraceContext, _impl_.flags_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // string tracestate = 4;
    {PROTOBUF_FIELD_OFFSET(PbTraceContext, _impl_.tracestate_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\32\0\0\0\12\0\0\0"
    "hpactor.net.PbTraceContext"
    "tracestate"
  }},
};
PROTOBUF_NOINLINE void PbTraceContext::Clear() {
// @@protoc_insertion_point(message_clear_start:hpactor.net.PbTraceContext)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.trace_id_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.span_id_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.tracestate_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.flags_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PbTraceContext::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PbTraceContext& this_ = static_cast<const PbTraceContext&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PbTraceContext::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PbTraceContext& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:hpactor.net.PbTraceContext)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bytes trace_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_trace_id().empty()) {
      const ::std::string& _s = this_._internal_trace_id();
      target = stream->WriteBytesMaybeAliased(1, _s, target);
    }
  }

  // bytes span_id = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_span_id().empty()) {
      const ::std::string& _s = this_._internal_span_id();
      target = stream->WriteBytesMaybeAliased(2, _s, target);
    }
  }

  // uint32 flags = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_flags() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          3, this_._internal_flags(), target);
    }
  }

  // string tracestate = 4;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_tracestate().empty()) {
      const ::std::string& _s = this_._internal_tracestate();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "hpactor.net.PbTraceContext.tracestate");
      target = stream->WriteStringMaybeAliased(4, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hpactor.net.PbTraceContext)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PbTraceContext::ByteSizeLong(const MessageLite& base) {
  const PbTraceContext& this_ = static_cast<const PbTraceContext&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PbTraceContext::ByteSizeLong() const {
  const PbTraceContext& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:hpactor.net.PbTraceContext)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // bytes trace_id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_trace_id().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_trace_id());
      }
    }
    // bytes span_id = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_span_id().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_span_id());
      }
    }
    // string tracestate = 4;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_tracestate().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_tracestate());
      }
    }
    // uint32 flags = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_flags() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_flags());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PbTraceContext::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<PbTraceContext*>(&to_msg);
  auto& from = static_cast<const PbTraceContext&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:hpactor.net.PbTraceContext)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_trace_id().empty()) {
        _this->_internal_set_trace_id(from._internal_trace_id());
      } else {
        if (_this->_impl_.trace_id_.IsDefault()) {
          _this->_internal_set_trace_id("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_span_id().empty()) {
        _this->_internal_set_span_id(from._internal_span_id());
      } else {
        if (_this->_impl_.span_id_.IsDefault()) {
          _this->_internal_set_span_id("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_tracestate().empty()) {
        _this->_internal_set_tracestate(from._internal_tracestate());
      } else {
        if (_this->_impl_.tracestate_.IsDefault()) {
          _this->_internal_set_tracestate("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_flags() != 0) {
        _this->_impl_.flags_ = from._impl_.flags_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PbTraceContext::CopyFrom(const PbTraceContext& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:hpactor.net.PbTraceContext)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PbTraceContext::InternalSwap(PbTraceContext* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.trace_id_, &other->_impl_.trace_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.span_id_, &other->_impl_.span_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.tracestate_, &other->_impl_.tracestate_, arena);
  swap(_impl_.flags_, other->_impl_.flags_);
}

::google::protobuf::Metadata PbTraceContext::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ActorMsgFrame::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ActorMsgFrame>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ActorMsgFrame, _impl_._has_bits_);
};

void ActorMsgFrame::clear_sender() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.sender_ != nullptr) _impl_.sender_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
void ActorMsgFrame::clear_receiver() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.receiver_ != nullptr) _impl_.receiver_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
ActorMsgFrame::ActorMsgFrame(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ActorMsgFrame_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:hpactor.net.ActorMsgFrame)
}
PROTOBUF_NDEBUG_INLINE ActorMsgFrame::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::hpactor::net::ActorMsgFrame& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        payload_(arena, from.payload_) {}

ActorMsgFrame::ActorMsgFrame(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ActorMsgFrame& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ActorMsgFrame_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ActorMsgFrame* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.sender_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.sender_)
                : nullptr;
  _impl_.receiver_ = (CheckHasBit(cached_has_bits, 0x00000004U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.receiver_)
                : nullptr;
  _impl_.trace_context_ = (CheckHasBit(cached_has_bits, 0x00000008U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.trace_context_)
                : nullptr;
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, message_id_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, message_id_),
           offsetof(Impl_, flags_) -
               offsetof(Impl_, message_id_) +
               sizeof(Impl_::flags_));

  // @@protoc_insertion_point(copy_constructor:hpactor.net.ActorMsgFrame)
}
PROTOBUF_NDEBUG_INLINE ActorMsgFrame::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        payload_(arena) {}

inline void ActorMsgFrame::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, sender_),
           0,
           offsetof(Impl_, flags_) -
               offsetof(Impl_, sender_) +
               sizeof(Impl_::flags_));
}
ActorMsgFrame::~ActorMsgFrame() {
  // @@protoc_insertion_point(destructor:hpactor.net.ActorMsgFrame)
  SharedDtor(*this);
}
inline void ActorMsgFrame::SharedDtor(MessageLite& self) {
  ActorMsgFrame& this_ = static_cast<ActorMsgFrame&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.payload_.Destroy();
  delete this_._impl_.sender_;
  delete this_._impl_.receiver_;
  delete this_._impl_.trace_context_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ActorMsgFrame::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ActorMsgFrame(arena);
}
constexpr auto ActorMsgFrame::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ActorMsgFrame),
                                            alignof(ActorMsgFrame));
}
constexpr auto ActorMsgFrame::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ActorMsgFrame_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &ActorMsgFrame::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ActorMsgFrame>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ActorMsgFrame::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ActorMsgFrame>(), &ActorMsgFrame::ByteSizeLong,
              &ActorMsgFrame::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ActorMsgFrame, _impl_._cached_size_),
          false,
      },
      &ActorMsgFrame::kDescriptorMethods,
      &descriptor_table_hpactor_2fframe_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ActorMsgFrame_class_data_ =
        ActorMsgFrame::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ActorMsgFrame::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ActorMsgFrame_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ActorMsgFrame_class_data_.tc_table);
  return ActorMsgFrame_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 3, 0, 2>
ActorMsgFrame::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ActorMsgFrame, _impl_._has_bits_),
    0, // no _extensions_
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    ActorMsgFrame_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::hpactor::net::ActorMsgFrame>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .hpactor.PbActorAddress sender = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 1, 0,
      PROTOBUF_FIELD_OFFSET(ActorMsgFrame, _impl_.sender_)}},
    // .hpactor.PbActorAddress receiver = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 2, 1,
      PROTOBUF_FIELD_OFFSET(ActorMsgFrame, _impl_.receiver_)}},
    // uint32 type_tag = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ActorMsgFrame, _impl_.type_tag_), 5>(),
     {24, 5, 0,
      PROTOBUF_FIELD_OFFSET(ActorMsgFrame, _impl_.type_tag_)}},
    // uint64 message_id = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ActorMsgFrame, _impl_.message_id_), 4>(),
     {32, 4, 0,
      PROTOBUF_FIELD_OFFSET(ActorMsgFrame, _impl_.message_id_)}},
    // uint32 flags = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ActorMsgFrame, _impl_.flags_), 6>(),
     {40, 6, 0,
      PROTOBUF_FIELD_OFFSET(ActorMsgFrame, _impl_.flags_)}},
    // bytes payload = 6;
    {::_pbi::TcParser::FastBS1,
     {50, 0, 0,
      PROTOBUF_FIELD_OFFSET(ActorMsgFrame, _impl_.payload_)}},
    // .hpactor.net.PbTraceContext trace_context = 7;
    {::_pbi::TcParser::FastMtS1,
     {58, 3, 2,
      PROTOBUF_FIELD_OFFSET(ActorMsgFrame, _impl_.trace_context_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .hpactor.PbActorAddress sender = 1;
    {PROTOBUF_FIELD_OFFSET(ActorMsgFrame, _impl_.sender_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .hpactor.PbActorAddress receiver = 2;
    {PROTOBUF_FIELD_OFFSET(ActorMsgFrame, _impl_.receiver_), _Internal::kHasBitsOffset + 2, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // uint32 type_tag = 3;
    {PROTOBUF_FIELD_OFFSET(ActorMsgFrame, _impl_.type_tag_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // uint64 message_id = 4;
    {PROTOBUF_FIELD_OFFSET(ActorMsgFrame, _impl_.message_id_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // uint32 flags = 5;
    {PROTOBUF_FIELD_OFFSET(ActorMsgFrame, _impl_.flags_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // bytes payload = 6;
    {PROTOBUF_FIELD_OFFSET(ActorMsgFrame, _impl_.payload_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // .hpactor.net.PbTraceContext trace_context = 7;
    {PROTOBUF_FIELD_OFFSET(ActorMsgFrame, _impl_.trace_context_), _Internal::kHasBitsOffset + 3, 2, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::hpactor::PbActorAddress>()},
      {::_pbi::TcParser::GetTable<::hpactor::PbActorAddress>()},
      {::_pbi::TcParser::GetTable<::hpactor::net::PbTraceContext>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void ActorMsgFrame::Clear() {
// @@protoc_insertion_point(message_clear_start:hpactor.net.ActorMsgFrame)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.payload_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.sender_ != nullptr);
      _impl_.sender_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(_impl_.receiver_ != nullptr);
      _impl_.receiver_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(_impl_.trace_context_ != nullptr);
      _impl_.trace_context_->Clear();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000070U)) {
    ::memset(&_impl_.message_id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.flags_) -
        reinterpret_cast<char*>(&_impl_.message_id_)) + sizeof(_impl_.flags_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ActorMsgFrame::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ActorMsgFrame& this_ = static_cast<const ActorMsgFrame&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ActorMsgFrame::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ActorMsgFrame& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:hpactor.net.ActorMsgFrame)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .hpactor.PbActorAddress sender = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.sender_, this_._impl_.sender_->GetCachedSize(), target,
        stream);
  }

  // .hpactor.PbActorAddress receiver = 2;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.receiver_, this_._impl_.receiver_->GetCachedSize(), target,
        stream);
  }

  // uint32 type_tag = 3;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (this_._internal_type_tag() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          3, this_._internal_type_tag(), target);
    }
  }

  // uint64 message_id = 4;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_message_id() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          4, this_._internal_message_id(), target);
    }
  }

  // uint32 flags = 5;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (this_._internal_flags() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          5, this_._internal_flags(), target);
    }
  }

  // bytes payload = 6;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_payload().empty()) {
      const ::std::string& _s = this_._internal_payload();
      target = stream->WriteBytesMaybeAliased(6, _s, target);
    }
  }

  // .hpactor.net.PbTraceContext trace_context = 7;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        7, *this_._impl_.trace_context_, this_._impl_.trace_context_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hpactor.net.ActorMsgFrame)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ActorMsgFrame::ByteSizeLong(const MessageLite& base) {
  const ActorMsgFrame& this_ = static_cast<const ActorMsgFrame&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ActorMsgFrame::ByteSizeLong() const {
  const ActorMsgFrame& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:hpactor.net.ActorMsgFrame)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    // bytes payload = 6;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_payload().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_payload());
      }
    }
    // .hpactor.PbActorAddress sender = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.sender_);
    }
    // .hpactor.PbActorAddress receiver = 2;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.receiver_);
    }
    // .hpactor.net.PbTraceContext trace_context = 7;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.trace_context_);
    }
    // uint64 message_id = 4;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_message_id() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_message_id());
      }
    }
    // uint32 type_tag = 3;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (this_._internal_type_tag() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_type_tag());
      }
    }
    // uint32 flags = 5;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (this_._internal_flags() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_flags());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ActorMsgFrame::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<ActorMsgFrame*>(&to_msg);
  auto& from = static_cast<const ActorMsgFrame&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:hpactor.net.ActorMsgFrame)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_payload().empty()) {
        _this->_internal_set_payload(from._internal_payload());
      } else {
        if (_this->_impl_.payload_.IsDefault()) {
          _this->_internal_set_payload("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.sender_ != nullptr);
      if (_this->_impl_.sender_ == nullptr) {
        _this->_impl_.sender_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.sender_);
      } else {
        _this->_impl_.sender_->MergeFrom(*from._impl_.sender_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(from._impl_.receiver_ != nullptr);
      if (_this->_impl_.receiver_ == nullptr) {
        _this->_impl_.receiver_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.receiver_);
      } else {
        _this->_impl_.receiver_->MergeFrom(*from._impl_.receiver_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(from._impl_.trace_context_ != nullptr);
      if (_this->_impl_.trace_context_ == nullptr) {
        _this->_impl_.trace_context_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.trace_context_);
      } else {
        _this->_impl_.trace_context_->MergeFrom(*from._impl_.trace_context_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_message_id() != 0) {
        _this->_impl_.message_id_ = from._impl_.message_id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (from._internal_type_tag() != 0) {
        _this->_impl_.type_tag_ = from._impl_.type_tag_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (from._internal_flags() != 0) {
        _this->_impl_.flags_ = from._impl_.flags_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ActorMsgFrame::CopyFrom(const ActorMsgFrame& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:hpactor.net.ActorMsgFrame)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ActorMsgFrame::InternalSwap(ActorMsgFrame* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.payload_, &other->_impl_.payload_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ActorMsgFrame, _impl_.flags_)
      + sizeof(ActorMsgFrame::_impl_.flags_)
      - PROTOBUF_FIELD_OFFSET(ActorMsgFrame, _impl_.sender_)>(
          reinterpret_cast<char*>(&_impl_.sender_),
          reinterpret_cast<char*>(&other->_impl_.sender_));
}

::google::protobuf::Metadata ActorMsgFrame::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace net
}  // namespace hpactor
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_hpactor_2fframe_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
