// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hpactor/frame.proto
// Protobuf C++ Version: 7.34.1

#ifndef hpactor_2fframe_2eproto_2epb_2eh
#define hpactor_2fframe_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7034001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "hpactor/common.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_hpactor_2fframe_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_hpactor_2fframe_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_hpactor_2fframe_2eproto;
}  // extern "C"
namespace hpactor {
namespace net {
class ActorMsgFrame;
struct ActorMsgFrameDefaultTypeInternal;
extern ActorMsgFrameDefaultTypeInternal _ActorMsgFrame_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ActorMsgFrame_class_data_;
class PbTraceContext;
struct PbTraceContextDefaultTypeInternal;
extern PbTraceContextDefaultTypeInternal _PbTraceContext_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PbTraceContext_class_data_;
}  // namespace net
}  // namespace hpactor
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace hpactor {
namespace net {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED PbTraceContext final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:hpactor.net.PbTraceContext) */ {
 public:
  inline PbTraceContext() : PbTraceContext(nullptr) {}
  ~PbTraceContext() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PbTraceContext* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PbTraceContext));
  }
#endif

  template <typename = void>
  explicit constexpr PbTraceContext(::google::protobuf::internal::ConstantInitialized);

  inline PbTraceContext(const PbTraceContext& from) : PbTraceContext(nullptr, from) {}
  inline PbTraceContext(PbTraceContext&& from) noexcept
      : PbTraceContext(nullptr, ::std::move(from)) {}
  inline PbTraceContext& operator=(const PbTraceContext& from) {
    CopyFrom(from);
    return *this;
  }
  inline PbTraceContext& operator=(PbTraceContext&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const PbTraceContext& default_instance() {
    return *reinterpret_cast<const PbTraceContext*>(
        &_PbTraceContext_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PbTraceContext& a, PbTraceContext& b) { a.Swap(&b); }
  inline void Swap(PbTraceContext* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PbTraceContext* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] PbTraceContext* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PbTraceContext>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PbTraceContext& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PbTraceContext& from) { PbTraceContext::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PbTraceContext* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "hpactor.net.PbTraceContext"; }

  explicit PbTraceContext(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PbTraceContext(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PbTraceContext& from);
  PbTraceContext(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PbTraceContext&& from) noexcept
      : PbTraceContext(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTraceIdFieldNumber = 1,
    kSpanIdFieldNumber = 2,
    kTracestateFieldNumber = 4,
    kFlagsFieldNumber = 3,
  };
  // bytes trace_id = 1;
  void clear_trace_id() ;
  [[nodiscard]] const ::std::string& trace_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_trace_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_trace_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_trace_id();
  void set_allocated_trace_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_trace_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_trace_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_trace_id();

  public:
  // bytes span_id = 2;
  void clear_span_id() ;
  [[nodiscard]] const ::std::string& span_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_span_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_span_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_span_id();
  void set_allocated_span_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_span_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_span_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_span_id();

  public:
  // string tracestate = 4;
  void clear_tracestate() ;
  [[nodiscard]] const ::std::string& tracestate() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_tracestate(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_tracestate();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_tracestate();
  void set_allocated_tracestate(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_tracestate() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_tracestate(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_tracestate();

  public:
  // uint32 flags = 3;
  void clear_flags() ;
  [[nodiscard]] ::uint32_t flags() const;
  void set_flags(::uint32_t value);

  private:
  ::uint32_t _internal_flags() const;
  void _internal_set_flags(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:hpactor.net.PbTraceContext)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 45,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PbTraceContext& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr trace_id_;
    ::google::protobuf::internal::ArenaStringPtr span_id_;
    ::google::protobuf::internal::ArenaStringPtr tracestate_;
    ::uint32_t flags_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_hpactor_2fframe_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PbTraceContext_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED ActorMsgFrame final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:hpactor.net.ActorMsgFrame) */ {
 public:
  inline ActorMsgFrame() : ActorMsgFrame(nullptr) {}
  ~ActorMsgFrame() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ActorMsgFrame* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ActorMsgFrame));
  }
#endif

  template <typename = void>
  explicit constexpr ActorMsgFrame(::google::protobuf::internal::ConstantInitialized);

  inline ActorMsgFrame(const ActorMsgFrame& from) : ActorMsgFrame(nullptr, from) {}
  inline ActorMsgFrame(ActorMsgFrame&& from) noexcept
      : ActorMsgFrame(nullptr, ::std::move(from)) {}
  inline ActorMsgFrame& operator=(const ActorMsgFrame& from) {
    CopyFrom(from);
    return *this;
  }
  inline ActorMsgFrame& operator=(ActorMsgFrame&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const ActorMsgFrame& default_instance() {
    return *reinterpret_cast<const ActorMsgFrame*>(
        &_ActorMsgFrame_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ActorMsgFrame& a, ActorMsgFrame& b) { a.Swap(&b); }
  inline void Swap(ActorMsgFrame* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ActorMsgFrame* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] ActorMsgFrame* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ActorMsgFrame>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ActorMsgFrame& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ActorMsgFrame& from) { ActorMsgFrame::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ActorMsgFrame* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "hpactor.net.ActorMsgFrame"; }

  explicit ActorMsgFrame(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ActorMsgFrame(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ActorMsgFrame& from);
  ActorMsgFrame(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ActorMsgFrame&& from) noexcept
      : ActorMsgFrame(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPayloadFieldNumber = 6,
    kSenderFieldNumber = 1,
    kReceiverFieldNumber = 2,
    kTraceContextFieldNumber = 7,
    kMessageIdFieldNumber = 4,
    kTypeTagFieldNumber = 3,
    kFlagsFieldNumber = 5,
  };
  // bytes payload = 6;
  void clear_payload() ;
  [[nodiscard]] const ::std::string& payload() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_payload(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_payload();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_payload();
  void set_allocated_payload(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_payload() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_payload(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_payload();

  public:
  // .hpactor.PbActorAddress sender = 1;
  [[nodiscard]] bool has_sender()
      const;
  void clear_sender() ;
  [[nodiscard]] const ::hpactor::PbActorAddress& sender() const;
  [[nodiscard]] ::hpactor::PbActorAddress* PROTOBUF_NULLABLE release_sender();
  ::hpactor::PbActorAddress* PROTOBUF_NONNULL mutable_sender();
  void set_allocated_sender(::hpactor::PbActorAddress* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_sender(::hpactor::PbActorAddress* PROTOBUF_NULLABLE value);
  ::hpactor::PbActorAddress* PROTOBUF_NULLABLE unsafe_arena_release_sender();

  private:
  const ::hpactor::PbActorAddress& _internal_sender() const;
  ::hpactor::PbActorAddress* PROTOBUF_NONNULL _internal_mutable_sender();

  public:
  // .hpactor.PbActorAddress receiver = 2;
  [[nodiscard]] bool has_receiver()
      const;
  void clear_receiver() ;
  [[nodiscard]] const ::hpactor::PbActorAddress& receiver() const;
  [[nodiscard]] ::hpactor::PbActorAddress* PROTOBUF_NULLABLE release_receiver();
  ::hpactor::PbActorAddress* PROTOBUF_NONNULL mutable_receiver();
  void set_allocated_receiver(::hpactor::PbActorAddress* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_receiver(::hpactor::PbActorAddress* PROTOBUF_NULLABLE value);
  ::hpactor::PbActorAddress* PROTOBUF_NULLABLE unsafe_arena_release_receiver();

  private:
  const ::hpactor::PbActorAddress& _internal_receiver() const;
  ::hpactor::PbActorAddress* PROTOBUF_NONNULL _internal_mutable_receiver();

  public:
  // .hpactor.net.PbTraceContext trace_context = 7;
  [[nodiscard]] bool has_trace_context()
      const;
  void clear_trace_context() ;
  [[nodiscard]] const ::hpactor::net::PbTraceContext& trace_context() const;
  [[nodiscard]] ::hpactor::net::PbTraceContext* PROTOBUF_NULLABLE release_trace_context();
  ::hpactor::net::PbTraceContext* PROTOBUF_NONNULL mutable_trace_context();
  void set_allocated_trace_context(::hpactor::net::PbTraceContext* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_trace_context(::hpactor::net::PbTraceContext* PROTOBUF_NULLABLE value);
  ::hpactor::net::PbTraceContext* PROTOBUF_NULLABLE unsafe_arena_release_trace_context();

  private:
  const ::hpactor::net::PbTraceContext& _internal_trace_context() const;
  ::hpactor::net::PbTraceContext* PROTOBUF_NONNULL _internal_mutable_trace_context();

  public:
  // uint64 message_id = 4;
  void clear_message_id() ;
  [[nodiscard]] ::uint64_t message_id() const;
  void set_message_id(::uint64_t value);

  private:
  ::uint64_t _internal_message_id() const;
  void _internal_set_message_id(::uint64_t value);

  public:
  // uint32 type_tag = 3;
  void clear_type_tag() ;
  [[nodiscard]] ::uint32_t type_tag() const;
  void set_type_tag(::uint32_t value);

  private:
  ::uint32_t _internal_type_tag() const;
  void _internal_set_type_tag(::uint32_t value);

  public:
  // uint32 flags = 5;
  void clear_flags() ;
  [[nodiscard]] ::uint32_t flags() const;
  void set_flags(::uint32_t value);

  private:
  ::uint32_t _internal_flags() const;
  void _internal_set_flags(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:hpactor.net.ActorMsgFrame)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 7,
                                   3, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ActorMsgFrame& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr payload_;
    ::hpactor::PbActorAddress* PROTOBUF_NULLABLE sender_;
    ::hpactor::PbActorAddress* PROTOBUF_NULLABLE receiver_;
    ::hpactor::net::PbTraceContext* PROTOBUF_NULLABLE trace_context_;
    ::uint64_t message_id_;
    ::uint32_t type_tag_;
    ::uint32_t flags_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_hpactor_2fframe_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ActorMsgFrame_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PbTraceContext

// bytes trace_id = 1;
inline void PbTraceContext::clear_trace_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.trace_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& PbTraceContext::trace_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:hpactor.net.PbTraceContext.trace_id)
  return _internal_trace_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PbTraceContext::set_trace_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.trace_id_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:hpactor.net.PbTraceContext.trace_id)
}
inline ::std::string* PROTOBUF_NONNULL PbTraceContext::mutable_trace_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_trace_id();
  // @@protoc_insertion_point(field_mutable:hpactor.net.PbTraceContext.trace_id)
  return _s;
}
inline const ::std::string& PbTraceContext::_internal_trace_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.trace_id_.Get();
}
inline void PbTraceContext::_internal_set_trace_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.trace_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PbTraceContext::_internal_mutable_trace_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.trace_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PbTraceContext::release_trace_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:hpactor.net.PbTraceContext.trace_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.trace_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.trace_id_.Set("", GetArena());
  }
  return released;
}
inline void PbTraceContext::set_allocated_trace_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.trace_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.trace_id_.IsDefault()) {
    _impl_.trace_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:hpactor.net.PbTraceContext.trace_id)
}

// bytes span_id = 2;
inline void PbTraceContext::clear_span_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.span_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& PbTraceContext::span_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:hpactor.net.PbTraceContext.span_id)
  return _internal_span_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PbTraceContext::set_span_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.span_id_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:hpactor.net.PbTraceContext.span_id)
}
inline ::std::string* PROTOBUF_NONNULL PbTraceContext::mutable_span_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_span_id();
  // @@protoc_insertion_point(field_mutable:hpactor.net.PbTraceContext.span_id)
  return _s;
}
inline const ::std::string& PbTraceContext::_internal_span_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.span_id_.Get();
}
inline void PbTraceContext::_internal_set_span_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.span_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PbTraceContext::_internal_mutable_span_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.span_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PbTraceContext::release_span_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:hpactor.net.PbTraceContext.span_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.span_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.span_id_.Set("", GetArena());
  }
  return released;
}
inline void PbTraceContext::set_allocated_span_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.span_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.span_id_.IsDefault()) {
    _impl_.span_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:hpactor.net.PbTraceContext.span_id)
}

// uint32 flags = 3;
inline void PbTraceContext::clear_flags() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.flags_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::uint32_t PbTraceContext::flags() const {
  // @@protoc_insertion_point(field_get:hpactor.net.PbTraceContext.flags)
  return _internal_flags();
}
inline void PbTraceContext::set_flags(::uint32_t value) {
  _internal_set_flags(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:hpactor.net.PbTraceContext.flags)
}
inline ::uint32_t PbTraceContext::_internal_flags() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.flags_;
}
inline void PbTraceContext::_internal_set_flags(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.flags_ = value;
}

// string tracestate = 4;
inline void PbTraceContext::clear_tracestate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tracestate_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& PbTraceContext::tracestate() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:hpactor.net.PbTraceContext.tracestate)
  return _internal_tracestate();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PbTraceContext::set_tracestate(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.tracestate_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:hpactor.net.PbTraceContext.tracestate)
}
inline ::std::string* PROTOBUF_NONNULL PbTraceContext::mutable_tracestate()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_tracestate();
  // @@protoc_insertion_point(field_mutable:hpactor.net.PbTraceContext.tracestate)
  return _s;
}
inline const ::std::string& PbTraceContext::_internal_tracestate() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tracestate_.Get();
}
inline void PbTraceContext::_internal_set_tracestate(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tracestate_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PbTraceContext::_internal_mutable_tracestate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.tracestate_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PbTraceContext::release_tracestate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:hpactor.net.PbTraceContext.tracestate)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.tracestate_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.tracestate_.Set("", GetArena());
  }
  return released;
}
inline void PbTraceContext::set_allocated_tracestate(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.tracestate_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.tracestate_.IsDefault()) {
    _impl_.tracestate_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:hpactor.net.PbTraceContext.tracestate)
}

// -------------------------------------------------------------------

// ActorMsgFrame

// .hpactor.PbActorAddress sender = 1;
inline bool ActorMsgFrame::has_sender() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.sender_ != nullptr);
  return value;
}
inline const ::hpactor::PbActorAddress& ActorMsgFrame::_internal_sender() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::hpactor::PbActorAddress* p = _impl_.sender_;
  return p != nullptr ? *p : reinterpret_cast<const ::hpactor::PbActorAddress&>(::hpactor::_PbActorAddress_default_instance_);
}
inline const ::hpactor::PbActorAddress& ActorMsgFrame::sender() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:hpactor.net.ActorMsgFrame.sender)
  return _internal_sender();
}
inline void ActorMsgFrame::unsafe_arena_set_allocated_sender(
    ::hpactor::PbActorAddress* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.sender_);
  }
  _impl_.sender_ = reinterpret_cast<::hpactor::PbActorAddress*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:hpactor.net.ActorMsgFrame.sender)
}
inline ::hpactor::PbActorAddress* PROTOBUF_NULLABLE ActorMsgFrame::release_sender() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::hpactor::PbActorAddress* released = _impl_.sender_;
  _impl_.sender_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::hpactor::PbActorAddress* PROTOBUF_NULLABLE ActorMsgFrame::unsafe_arena_release_sender() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:hpactor.net.ActorMsgFrame.sender)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::hpactor::PbActorAddress* temp = _impl_.sender_;
  _impl_.sender_ = nullptr;
  return temp;
}
inline ::hpactor::PbActorAddress* PROTOBUF_NONNULL ActorMsgFrame::_internal_mutable_sender() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.sender_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::hpactor::PbActorAddress>(GetArena());
    _impl_.sender_ = reinterpret_cast<::hpactor::PbActorAddress*>(p);
  }
  return _impl_.sender_;
}
inline ::hpactor::PbActorAddress* PROTOBUF_NONNULL ActorMsgFrame::mutable_sender()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::hpactor::PbActorAddress* _msg = _internal_mutable_sender();
  // @@protoc_insertion_point(field_mutable:hpactor.net.ActorMsgFrame.sender)
  return _msg;
}
inline void ActorMsgFrame::set_allocated_sender(::hpactor::PbActorAddress* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.sender_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.sender_ = reinterpret_cast<::hpactor::PbActorAddress*>(value);
  // @@protoc_insertion_point(field_set_allocated:hpactor.net.ActorMsgFrame.sender)
}

// .hpactor.PbActorAddress receiver = 2;
inline bool ActorMsgFrame::has_receiver() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  PROTOBUF_ASSUME(!value || _impl_.receiver_ != nullptr);
  return value;
}
inline const ::hpactor::PbActorAddress& ActorMsgFrame::_internal_receiver() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::hpactor::PbActorAddress* p = _impl_.receiver_;
  return p != nullptr ? *p : reinterpret_cast<const ::hpactor::PbActorAddress&>(::hpactor::_PbActorAddress_default_instance_);
}
inline const ::hpactor::PbActorAddress& ActorMsgFrame::receiver() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:hpactor.net.ActorMsgFrame.receiver)
  return _internal_receiver();
}
inline void ActorMsgFrame::unsafe_arena_set_allocated_receiver(
    ::hpactor::PbActorAddress* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.receiver_);
  }
  _impl_.receiver_ = reinterpret_cast<::hpactor::PbActorAddress*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:hpactor.net.ActorMsgFrame.receiver)
}
inline ::hpactor::PbActorAddress* PROTOBUF_NULLABLE ActorMsgFrame::release_receiver() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::hpactor::PbActorAddress* released = _impl_.receiver_;
  _impl_.receiver_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::hpactor::PbActorAddress* PROTOBUF_NULLABLE ActorMsgFrame::unsafe_arena_release_receiver() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:hpactor.net.ActorMsgFrame.receiver)

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::hpactor::PbActorAddress* temp = _impl_.receiver_;
  _impl_.receiver_ = nullptr;
  return temp;
}
inline ::hpactor::PbActorAddress* PROTOBUF_NONNULL ActorMsgFrame::_internal_mutable_receiver() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.receiver_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::hpactor::PbActorAddress>(GetArena());
    _impl_.receiver_ = reinterpret_cast<::hpactor::PbActorAddress*>(p);
  }
  return _impl_.receiver_;
}
inline ::hpactor::PbActorAddress* PROTOBUF_NONNULL ActorMsgFrame::mutable_receiver()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::hpactor::PbActorAddress* _msg = _internal_mutable_receiver();
  // @@protoc_insertion_point(field_mutable:hpactor.net.ActorMsgFrame.receiver)
  return _msg;
}
inline void ActorMsgFrame::set_allocated_receiver(::hpactor::PbActorAddress* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.receiver_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }

  _impl_.receiver_ = reinterpret_cast<::hpactor::PbActorAddress*>(value);
  // @@protoc_insertion_point(field_set_allocated:hpactor.net.ActorMsgFrame.receiver)
}

// uint32 type_tag = 3;
inline void ActorMsgFrame::clear_type_tag() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_tag_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::uint32_t ActorMsgFrame::type_tag() const {
  // @@protoc_insertion_point(field_get:hpactor.net.ActorMsgFrame.type_tag)
  return _internal_type_tag();
}
inline void ActorMsgFrame::set_type_tag(::uint32_t value) {
  _internal_set_type_tag(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:hpactor.net.ActorMsgFrame.type_tag)
}
inline ::uint32_t ActorMsgFrame::_internal_type_tag() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.type_tag_;
}
inline void ActorMsgFrame::_internal_set_type_tag(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_tag_ = value;
}

// uint64 message_id = 4;
inline void ActorMsgFrame::clear_message_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_id_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::uint64_t ActorMsgFrame::message_id() const {
  // @@protoc_insertion_point(field_get:hpactor.net.ActorMsgFrame.message_id)
  return _internal_message_id();
}
inline void ActorMsgFrame::set_message_id(::uint64_t value) {
  _internal_set_message_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:hpactor.net.ActorMsgFrame.message_id)
}
inline ::uint64_t ActorMsgFrame::_internal_message_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.message_id_;
}
inline void ActorMsgFrame::_internal_set_message_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_id_ = value;
}

// uint32 flags = 5;
inline void ActorMsgFrame::clear_flags() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.flags_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline ::uint32_t ActorMsgFrame::flags() const {
  // @@protoc_insertion_point(field_get:hpactor.net.ActorMsgFrame.flags)
  return _internal_flags();
}
inline void ActorMsgFrame::set_flags(::uint32_t value) {
  _internal_set_flags(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:hpactor.net.ActorMsgFrame.flags)
}
inline ::uint32_t ActorMsgFrame::_internal_flags() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.flags_;
}
inline void ActorMsgFrame::_internal_set_flags(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.flags_ = value;
}

// bytes payload = 6;
inline void ActorMsgFrame::clear_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.payload_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& ActorMsgFrame::payload() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:hpactor.net.ActorMsgFrame.payload)
  return _internal_payload();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ActorMsgFrame::set_payload(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.payload_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:hpactor.net.ActorMsgFrame.payload)
}
inline ::std::string* PROTOBUF_NONNULL ActorMsgFrame::mutable_payload()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_payload();
  // @@protoc_insertion_point(field_mutable:hpactor.net.ActorMsgFrame.payload)
  return _s;
}
inline const ::std::string& ActorMsgFrame::_internal_payload() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.payload_.Get();
}
inline void ActorMsgFrame::_internal_set_payload(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.payload_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ActorMsgFrame::_internal_mutable_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.payload_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ActorMsgFrame::release_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:hpactor.net.ActorMsgFrame.payload)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.payload_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.payload_.Set("", GetArena());
  }
  return released;
}
inline void ActorMsgFrame::set_allocated_payload(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.payload_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.payload_.IsDefault()) {
    _impl_.payload_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:hpactor.net.ActorMsgFrame.payload)
}

// .hpactor.net.PbTraceContext trace_context = 7;
inline bool ActorMsgFrame::has_trace_context() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  PROTOBUF_ASSUME(!value || _impl_.trace_context_ != nullptr);
  return value;
}
inline void ActorMsgFrame::clear_trace_context() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.trace_context_ != nullptr) _impl_.trace_context_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::hpactor::net::PbTraceContext& ActorMsgFrame::_internal_trace_context() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::hpactor::net::PbTraceContext* p = _impl_.trace_context_;
  return p != nullptr ? *p : reinterpret_cast<const ::hpactor::net::PbTraceContext&>(::hpactor::net::_PbTraceContext_default_instance_);
}
inline const ::hpactor::net::PbTraceContext& ActorMsgFrame::trace_context() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:hpactor.net.ActorMsgFrame.trace_context)
  return _internal_trace_context();
}
inline void ActorMsgFrame::unsafe_arena_set_allocated_trace_context(
    ::hpactor::net::PbTraceContext* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.trace_context_);
  }
  _impl_.trace_context_ = reinterpret_cast<::hpactor::net::PbTraceContext*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:hpactor.net.ActorMsgFrame.trace_context)
}
inline ::hpactor::net::PbTraceContext* PROTOBUF_NULLABLE ActorMsgFrame::release_trace_context() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::hpactor::net::PbTraceContext* released = _impl_.trace_context_;
  _impl_.trace_context_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::hpactor::net::PbTraceContext* PROTOBUF_NULLABLE ActorMsgFrame::unsafe_arena_release_trace_context() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:hpactor.net.ActorMsgFrame.trace_context)

  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::hpactor::net::PbTraceContext* temp = _impl_.trace_context_;
  _impl_.trace_context_ = nullptr;
  return temp;
}
inline ::hpactor::net::PbTraceContext* PROTOBUF_NONNULL ActorMsgFrame::_internal_mutable_trace_context() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.trace_context_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::hpactor::net::PbTraceContext>(GetArena());
    _impl_.trace_context_ = reinterpret_cast<::hpactor::net::PbTraceContext*>(p);
  }
  return _impl_.trace_context_;
}
inline ::hpactor::net::PbTraceContext* PROTOBUF_NONNULL ActorMsgFrame::mutable_trace_context()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::hpactor::net::PbTraceContext* _msg = _internal_mutable_trace_context();
  // @@protoc_insertion_point(field_mutable:hpactor.net.ActorMsgFrame.trace_context)
  return _msg;
}
inline void ActorMsgFrame::set_allocated_trace_context(::hpactor::net::PbTraceContext* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.trace_context_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }

  _impl_.trace_context_ = reinterpret_cast<::hpactor::net::PbTraceContext*>(value);
  // @@protoc_insertion_point(field_set_allocated:hpactor.net.ActorMsgFrame.trace_context)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace net
}  // namespace hpactor


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif // hpactor_2fframe_2eproto_2epb_2eh
