add_executable(test_async_actor test_async_actor.cpp)
target_link_libraries(test_async_actor hpactor)
add_test(NAME test_async_actor COMMAND test_async_actor)

add_executable(test_actor_type_registry test_actor_type_registry.cpp)
target_link_libraries(test_actor_type_registry hpactor)
add_test(NAME test_actor_type_registry COMMAND test_actor_type_registry)

add_executable(test_spawn_receiver test_spawn_receiver.cpp)
target_link_libraries(test_spawn_receiver hpactor)
add_test(NAME test_spawn_receiver COMMAND test_spawn_receiver)

add_executable(test_spawn_serialization test_spawn_serialization.cpp)
target_link_libraries(test_spawn_serialization hpactor)
add_test(NAME test_spawn_serialization COMMAND test_spawn_serialization)

add_executable(test_spawn_integration test_spawn_integration.cpp)
target_link_libraries(test_spawn_integration hpactor)
add_test(NAME test_spawn_integration COMMAND test_spawn_integration)