if(EXISTS "/Users/skg7on/Workspace/Projects/HPActor/.claude/worktrees/refactor-actor-system-v2/build-main/tests/unit/sched/test_unit_sched[1]_tests.cmake")
  include("/Users/skg7on/Workspace/Projects/HPActor/.claude/worktrees/refactor-actor-system-v2/build-main/tests/unit/sched/test_unit_sched[1]_tests.cmake")
else()
  add_test(test_unit_sched_NOT_BUILT test_unit_sched_NOT_BUILT)
endif()
