if(EXISTS "/Users/skg7on/Workspace/Projects/HPActor/.claude/worktrees/refactor-actor-system-v2/build-main/tests/unit/types/test_request_timeout[1]_tests.cmake")
  include("/Users/skg7on/Workspace/Projects/HPActor/.claude/worktrees/refactor-actor-system-v2/build-main/tests/unit/types/test_request_timeout[1]_tests.cmake")
else()
  add_test(test_request_timeout_NOT_BUILT test_request_timeout_NOT_BUILT)
endif()
