# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hpactor/cli.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11hpactor/cli.proto\x12\x0bhpactor.cli\"\xc5\x01\n\nCliCommand\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x33\n\x06params\x18\x02 \x03(\x0b\x32#.hpactor.cli.CliCommand.ParamsEntry\x12\x0c\n\x04\x61rgs\x18\x03 \x03(\t\x12\x0e\n\x06\x66ormat\x18\x04 \x01(\t\x12\x12\n\nrpc_method\x18\x05 \x01(\t\x12\x13\n\x0brpc_request\x18\x06 \x01(\x0c\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"q\n\x0b\x43liResponse\x12\x14\n\x0c\x63ontent_type\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12\x10\n\x08is_error\x18\x03 \x01(\x08\x12\x12\n\nerror_code\x18\x04 \x01(\x05\x12\x15\n\ris_structured\x18\x05 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hpactor.cli_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLICOMMAND_PARAMSENTRY._options = None
  _CLICOMMAND_PARAMSENTRY._serialized_options = b'8\001'
  _CLICOMMAND._serialized_start=35
  _CLICOMMAND._serialized_end=232
  _CLICOMMAND_PARAMSENTRY._serialized_start=187
  _CLICOMMAND_PARAMSENTRY._serialized_end=232
  _CLIRESPONSE._serialized_start=234
  _CLIRESPONSE._serialized_end=347
# @@protoc_insertion_point(module_scope)
