add_subdirectory(core)
add_subdirectory(adt)
add_subdirectory(mailbox)
add_subdirectory(sched)
add_subdirectory(mem)
if(ENABLE_CLI)
    add_subdirectory(cli)
endif()
add_subdirectory(config)
add_subdirectory(ref)
add_subdirectory(log)
if(ENABLE_ACTOR_TRACING)
    add_subdirectory(tracing)
endif()
add_subdirectory(net)
add_subdirectory(supervision)
add_subdirectory(actor)
add_subdirectory(spawn)
add_subdirectory(fault)
add_subdirectory(types)
add_subdirectory(msg)
add_subdirectory(timer)
if(ENABLE_AI_ACCELERATORS)
    add_subdirectory(ai)
endif()
add_subdirectory(process)
add_subdirectory(apps)
add_subdirectory(saturate)
add_subdirectory(cluster)
add_subdirectory(runtime)
if(ENABLE_PYTHON_BINDINGS)
    add_subdirectory(python)
endif()
