add_subdirectory(core)
# TODO(Task 6): add_subdirectory(adt)
# TODO(Task 7): add_subdirectory(mailbox)
# TODO(Task 8): add_subdirectory(sched)
# TODO(Task 9): add_subdirectory(mem)
# TODO(Task 10): if(ENABLE_CLI)
#     add_subdirectory(cli)
# endif()
# TODO(Task 10): add_subdirectory(config)
# TODO(Task 10): add_subdirectory(ref)
# TODO(Task 11): add_subdirectory(log)
# TODO(Task 11): if(ENABLE_ACTOR_TRACING)
#     add_subdirectory(tracing)
# endif()
# TODO(Task 11): add_subdirectory(net)
# TODO(Task 11): add_subdirectory(supervision)
# TODO(Task 11): add_subdirectory(actor)
# TODO(Task 11): add_subdirectory(spawn)
