add_subdirectory(core)
add_subdirectory(adt)
add_subdirectory(mailbox)
add_subdirectory(sched)
add_subdirectory(mem)
if(ENABLE_CLI)
    add_subdirectory(cli)
endif()
add_subdirectory(config)
add_subdirectory(ref)
add_subdirectory(log)
if(ENABLE_ACTOR_TRACING)
    add_subdirectory(tracing)
endif()
add_subdirectory(net)
add_subdirectory(supervision)
add_subdirectory(actor)
add_subdirectory(spawn)
