// Copyright 2026 HPActor Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

// =============================================================================
// HPActor Configuration
// =============================================================================
//
// This header provides macros for conditional compilation based on available
// C++ features. It is generated by CMake based on compiler capabilities.
//
// Key macros:
//   HPACTOR_USE_COROUTINES  - 1 if C++20 coroutines are available, 0 otherwise
//   HPACTOR_HAVE_COROUTINE_HEADER - 1 if <coroutine> header is available
//
// =============================================================================

// Detect if CMake set up coroutine support
#if defined(HPACTOR_USE_COROUTINES) && HPACTOR_USE_COROUTINES
    #define HPACTOR_USE_COROUTINES 1
#else
    #define HPACTOR_USE_COROUTINES 0
#endif

// Convenience macro for guarding coroutine-specific code
#if HPACTOR_USE_COROUTINES
    #define HPACTOR_IF_COROUTINES(...) __VA_ARGS__
    #define HPACTOR_IF_NO_COROUTINES(...)
#else
    #define HPACTOR_IF_COROUTINES(...)
    #define HPACTOR_IF_NO_COROUTINES(...) __VA_ARGS__
#endif
